# Generated by Django 5.0 on 2023-12-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orvasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanics',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
